import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"通信网 · Phase 3 MVP","description":"","frontmatter":{},"headers":[],"relativePath":"telecom/index.md","filePath":"telecom/index.md"}');
const _sfc_main = { name: "telecom/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="通信网-·-phase-3-mvp" tabindex="-1">通信网 · Phase 3 MVP <a class="header-anchor" href="#通信网-·-phase-3-mvp" aria-label="Permalink to &quot;通信网 · Phase 3 MVP&quot;">​</a></h1><p>草果地图通信网组件包 <code>@caoguo/maplibre-telecom</code>，聚焦通信网（基站覆盖 / 信号热力 / 网络健康）， 交付<strong>基站覆盖地图、网络健康度面板</strong> 2 类组件 + 覆盖分析算法。</p><h2 id="模块组成" tabindex="-1">模块组成 <a class="header-anchor" href="#模块组成" aria-label="Permalink to &quot;模块组成&quot;">​</a></h2><table tabindex="0"><thead><tr><th>模块</th><th>路径</th><th>能力</th></tr></thead><tbody><tr><td>CellCoverage</td><td><a href="/demo/telecom/coverage"><code>/telecom/coverage</code></a></td><td>基站按运营商/技术着色 + 覆盖区域叠加 + 盲区识别 + 扇区可视化</td></tr><tr><td>NetworkHealth</td><td><a href="/demo/telecom/health"><code>/telecom/health</code></a></td><td>在线率统计 + 故障告警 + 故障趋势</td></tr></tbody></table><h2 id="设计要点" tabindex="-1">设计要点 <a class="header-anchor" href="#设计要点" aria-label="Permalink to &quot;设计要点&quot;">​</a></h2><ol><li><p><strong>算法纯函数 + 渲染薄壳</strong></p><ul><li>覆盖盲区识别（射线法）、重叠率计算、故障趋势聚合均为纯函数</li></ul></li><li><p><strong>着色规则</strong>（PRD §5.1.3）</p><ul><li>基站按运营商：移动绿 / 联通红 / 电信蓝 / 广电橙</li><li>信号强度（RSRP）热力：极弱红 → 弱橙 → 一般黄 → 好绿 → 极好青</li></ul></li><li><p><strong>运营商品牌主题</strong>（PRD §5.3）</p><ul><li>三大运营商预设品牌主题，一键切换</li></ul></li></ol><h2 id="演示数据" tabindex="-1">演示数据 <a class="header-anchor" href="#演示数据" aria-label="Permalink to &quot;演示数据&quot;">​</a></h2><p>演示使用武汉模拟通信网（合成数据，含 5 基站 + 5 覆盖区域 + 8 信号采样点）。 详见 <code>apps/demo/data/wuhan-telecom.ts</code>。</p><h2 id="快速集成示例" tabindex="-1">快速集成示例 <a class="header-anchor" href="#快速集成示例" aria-label="Permalink to &quot;快速集成示例&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { CaoguoMap } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;@caoguo/maplibre&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { CellCoverage, NetworkHealth } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;@caoguo/maplibre-telecom&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> map</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> CaoguoMap</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">({ container, center, zoom });</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">map.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">on</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;load&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">, () </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=&gt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">  // 1) 基站覆盖</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> coverage</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> CellCoverage</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">({ map, dataset, colorBy: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;carrier&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> });</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  coverage.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">render</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">();</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">  // 2) 网络健康度</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> health</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> new</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> NetworkHealth</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">({ dataset });</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> rate</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> health.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">onlineRateByCarrier</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">();</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">});</span></span></code></pre></div><h2 id="路线图" tabindex="-1">路线图 <a class="header-anchor" href="#路线图" aria-label="Permalink to &quot;路线图&quot;">​</a></h2><ul><li><strong>Phase 3（当前）</strong> - 基站覆盖 / 网络健康（2 个 MVP）</li><li><strong>后续</strong> - 接入真实 MR 数据 + 覆盖仿真 + 网络优化建议</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("telecom/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
